logFilters:
  - code: YN0032
    level: discard
  - code: YN0061
    level: discard

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-bump.cjs
    spec: 'https://github.com/cometkim/yarn-plugin-bump/releases/download/v0.0.7/plugin-bump.js'

yarnPath: .yarn/releases/yarn-2.4.1.cjs
