plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: '@yarnpkg/plugin-typescript'
  - path: .yarn/plugins/@yarnpkg/plugin-bump.cjs
    spec: 'https://github.com/cometkim/yarn-plugin-bump/releases/download/v0.0.7/plugin-bump.js'
  - path: .yarn/plugins/@ojkelly/plugin-build.cjs
    spec: 'https://yarn.build/latest'

yarnPath: .yarn/releases/yarn-berry.cjs
