// Generated by https://quicktype.io

export interface MDNResult {
	query: string;
	locale: Locale;
	page: number;
	pages: number;
	start: number;
	end: number;
	next: string;
	previous: null;
	count: number;
	filters: Filter[];
	documents: Document[];
}

export interface Document {
	title: string;
	slug: string;
	locale: Locale;
	summary: string;
}

export enum Locale {
	EnUS = 'en-US',
}

export interface Filter {
	name: string;
	slug: string;
	options: Option[];
}

export interface Option {
	name: string;
	slug: string;
	count: number;
	active: boolean;
	urls: Urls;
}

export interface Urls {
	active: string;
	inactive: Inactive;
}

export enum Inactive {
	APIV1SearchEnUSQString = '/api/v1/search/en-US?q=String',
}
