name: Dependency Bumper
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  bump-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Bump up Yarn 2 dependencies
        uses: cometkim/yarn-plugin-bump@master
        with:
          branch: dependencies/all

      - name: Sync dependency update branch with Pull Request
        uses: vsoch/pull-request-action@1.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_FROM_BRANCH: dependencies/all
