name: Dependabot

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    # if: github.actor == 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
          persist-credentials: false # minimize exposure
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12'
      # - name: Remove yarn.lock
      #   run:
      - name: WORK
        run: github.branch
      # - name: Build
      #   run: yarn up '*'
      # - name: Commit
      #   run: git config user.name github-actions && git config user.email github-actions@github.com && git add . && git commit -m "Dependabot fix 🚀"
