name: Run Tokei
on: push
jobs:
  RunTokei:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: install
          args: tokei
      - uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const child_process = require('child_process');
            const tokei = child_process.execSync('tokei').toString();
            ;(async() => {
              const d = await github.request('POST /repos/:owner/:repo/commits/:sha/comments', {
                owner: context.repo.owner,
                repo: context.repo.repo,
                sha: context.sha,
                body: `**Tokei**:\n \`\`\`\n${tokei}\`\`\``
              });
            })();
